#!MC 1410
$!READDATASET  '".new.plt" ".old.plt"'
  READDATAOPTION = NEW
  RESETSTYLE = YES
  VARLOADMODE = BYNAME
  ASSIGNSTRANDIDS = YES
  VARLIST =  [3-8]
$!FIELDLAYERS SHOWMESH = YES
$!REDRAWALL
$!KRIG
  SOURCEZONES =  [2]
  DESTINATIONZONE = 1
  VARLIST =  [3-8]
  KRIGRANGE = 0.3
  KRIGZEROVALUE = 0
  KRIGDRIFT = LINEAR
  INTERPPTSELECTION = OCTANTNPOINTS
  INTERPNPOINTS = 8
$!WRITEDATASET  "solution.plt"
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDEDATASHARELINKAGE = YES
  ZONELIST =  [1]
  BINARY = YES
  USEPOINTFORMAT = NO
  PRECISION = 9
  TECPLOTVERSIONTOWRITE = TECPLOTCURRENT
